/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

export class Security extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=apiKey;subtype=header;name=x-client-secret",
    })
    clientSecret: string;

    @SpeakeasyMetadata({
        data: "security, scheme=true;type=apiKey;subtype=header;name=x-project-id",
    })
    projectId: string;
}
