/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class DisableRoyaltyInformationRequest extends SpeakeasyBase {
    /**
     * Collection identifier. For pre-built collections use IDs 'default-solana' or 'default-polygon'. use the result of the [`create-collection`](https://docs.crossmint.com/reference/create-collection) endpoint to get the identifier for custom collections.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=collectionId" })
    collectionId: string;
}

export class DisableRoyaltyInformationResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
