/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class GetRoyaltyInformationRequest extends SpeakeasyBase {
    /**
     * Collection identifier. For pre-built collections use IDs 'default-solana' or 'default-polygon'. use the result of the [`create-collection`](https://docs.crossmint.com/reference/create-collection) endpoint to get the identifier for custom collections.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=collectionId" })
    collectionId: string;
}

export class GetRoyaltyInformation200ApplicationJSONRecipients extends SpeakeasyBase {
    /**
     * Recipient address. e.g., 0x71C...
     */
    @SpeakeasyMetadata()
    @Expose({ name: "address" })
    address?: string;

    /**
     * A basis point is a standard measure for percentages in finance. One basis point equals 1/100th of 1%, or 0.01%.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "basisPoints" })
    basisPoints?: number;
}

/**
 * Success.
 */
export class GetRoyaltyInformation200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: GetRoyaltyInformation200ApplicationJSONRecipients })
    @Expose({ name: "recipients" })
    @Type(() => GetRoyaltyInformation200ApplicationJSONRecipients)
    recipients?: GetRoyaltyInformation200ApplicationJSONRecipients[];
}

export class GetRoyaltyInformationResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Success.
     */
    @SpeakeasyMetadata()
    getRoyaltyInformation200ApplicationJSONObject?: GetRoyaltyInformation200ApplicationJSON;
}
