/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

/**
 * Display name of your attribute
 */
export enum MintNftAlphaRequestBodyMetadataMetadataObjectAttributesDisplayType {
    BoostNumber = "boost_number",
    BoostPercentage = "boost_percentage",
    Number = "number",
}

export class MintNftAlphaRequestBodyMetadataMetadataObjectAttributes extends SpeakeasyBase {
    /**
     * Display name of your attribute
     */
    @SpeakeasyMetadata()
    @Expose({ name: "display_type" })
    displayType?: MintNftAlphaRequestBodyMetadataMetadataObjectAttributesDisplayType;

    /**
     * The name of the trait
     */
    @SpeakeasyMetadata()
    @Expose({ name: "trait_type" })
    traitType: string;

    /**
     * The value of the trait
     */
    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value: string;
}

/**
 * See https://docs.crossmint.com/docs/metadata for more info.
 */
export class MintNftAlphaRequestBodyMetadataMetadataObject extends SpeakeasyBase {
    /**
     * (Optional) [Polygon only] <br> The Mint API natively supports rich metadata within ERC 721 and ERC 1155, including audio, video and/or HTML. <br> Populate the animation_url field as per the OpenSea metadata spec: <br> https://docs.opensea.io/docs/metadata-standards#metadata-structure
     */
    @SpeakeasyMetadata()
    @Expose({ name: "animation_url" })
    animationUrl?: string;

    /**
     * (Optional) Add attributes to your NFT
     */
    @SpeakeasyMetadata({ elemType: MintNftAlphaRequestBodyMetadataMetadataObjectAttributes })
    @Expose({ name: "attributes" })
    @Type(() => MintNftAlphaRequestBodyMetadataMetadataObjectAttributes)
    attributes?: MintNftAlphaRequestBodyMetadataMetadataObjectAttributes[];

    /**
     * A quick and brief description of your NFT (Max length: 64)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    /**
     * Direct link to your NFT image
     */
    @SpeakeasyMetadata()
    @Expose({ name: "image" })
    image?: string;

    /**
     * The name of your NFT (Max length: 32)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}

export class MintNftAlphaRequestBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    metadata: any;

    /**
     * Recipient address in the format of `<chain>:<address>` or <br> `email:<email_address>:<chain>`.
     *
     * @remarks
     * See https://docs.crossmint.com/docs/recipients for more info.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "recipient" })
    recipient?: string;

    /**
     * (Optional) Any URLs in the metadata object will be resolved and reuploaded to IPFS [Default: true]
     */
    @SpeakeasyMetadata()
    @Expose({ name: "reuploadLinkedFiles" })
    reuploadLinkedFiles?: boolean;
}

export class MintNftAlphaRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    requestBody?: MintNftAlphaRequestBody;

    /**
     * Every project can mint to their pre-built collections (with IDs 'default-solana' or 'default-polygon'),  or use the [`create-collection`](https://docs.crossmint.com/reference/create-collection) endpoint
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=collectionId" })
    collectionId: string;
}

export class MintNftAlpha200ApplicationJSONOnchain extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "chain" })
    chain: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: string;
}

/**
 * Success.
 */
export class MintNftAlpha200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "onchain" })
    @Type(() => MintNftAlpha200ApplicationJSONOnchain)
    onchain?: MintNftAlpha200ApplicationJSONOnchain;
}

export class MintNftAlphaResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Invalid arguments, please make sure you're following the api specification.
     */
    @SpeakeasyMetadata()
    error?: shared.ErrorT;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * Success.
     */
    @SpeakeasyMetadata()
    mintNftAlpha200ApplicationJSONObject?: MintNftAlpha200ApplicationJSON;
}
